5.1 had a very annoying issue with the name of my bookapp and the instructor copy. My version wasn't launching because it was getting several exceptions(i.e. NoClassDefFoundError) being thrown that it was looking for the instructor copy. Had to download copy off of GitHub. Thank you Jim for enforcing Commit offen and early because i didn't lose any work.